server:
  port: 8081

spring:
  application:
    name: user-service

spring:
  datasource:
    url: jdbc:postgresql://${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
