server:
  port: 8081

spring:
  application:
    name: user-service

spring:
  datasource:
    url: jdbc:postgresql://postgres-user:5432/userdb
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
